version: "3.7"

services:
  app:
    build: .
    container_name: "springapp"
    depends_on:
        - mongodb
    ports:
        - "8080:8080"

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
        - "27017:27017"
